# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
    defaultNetwork.settings.dns_enabled = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."gluetun" = {
    image = "qmcgaw/gluetun";
    environment = {
      "OPENVPN_USER" = "p3881393";
      "SERVER_REGIONS" = "US West Streaming Optimized";
      "VPN_SERVICE_PROVIDER" = "private internet access";
      "VPN_TYPE" = "openvpn";
      "OPENVPN_PROTOCOL" = "tcp";
      "OPENVPN_TARGET_PORT"= "443";
    };
    environmentFiles = [ /run/secrets/openvpn/password ];
    volumes = [
      "/var/lib/gluetun:/gluetun:rw"
    ];
    ports = [
      "8888:8888/tcp"
      "8388:8388/tcp"
      "8388:8388/udp"
      "8080:8080/tcp" #sabnzbd
      "7979:7979/tcp" #qbittorrent
      "49420:49420/tcp"
      "49420:49420/udp"
      "6882:6882/tcp"
      "6882:6882/udp"
      "9191:9191/tcp" #dispatcharr
      "9191:9191/udp" #dispatcharr
    ];
    log-driver = "journald";
    extraOptions = [
      "--cap-add=NET_ADMIN"
      "--device=/dev/net/tun:/dev/net/tun:rwm"
      "--network-alias=gluetun"
      "--network=downloads_default"
    ];
  };
  systemd.services."podman-gluetun" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "podman-network-downloads_default.service"
    ];
    requires = [
      "podman-network-downloads_default.service"
    ];
    partOf = [
      "podman-compose-downloads-root.target"
    ];
    wantedBy = [
      "podman-compose-downloads-root.target"
    ];
  };
  virtualisation.oci-containers.containers."qbittorrent" = {
    image = "lscr.io/linuxserver/qbittorrent:latest";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "America/Los_Angeles";
      "WEBUI_PORT" = "7979";
    };
    volumes = [
      "/var/lib/qBittorrent/qBittorrent/config:/config:rw"
      "/mnt/data/downloads:/downloads:rw"
    ];
    dependsOn = [
      "gluetun"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network=container:gluetun"
    ];
  };
  systemd.services."podman-qbittorrent" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    partOf = [
      "podman-compose-downloads-root.target"
    ];
    wantedBy = [
      "podman-compose-downloads-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-downloads_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f downloads_default";
    };
    script = ''
      podman network inspect downloads_default || podman network create downloads_default
    '';
    partOf = [ "podman-compose-downloads-root.target" ];
    wantedBy = [ "podman-compose-downloads-root.target" ];
  };

  virtualisation.oci-containers.containers."sabnzbd" = {
    image = "ghcr.io/linuxserver/sabnzbd";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "America/Los_Angeles";
    };
    volumes = [
      "/var/lib/sabnzbd/config:/config:rw"
      "/var/lib/sabnzbd/scripts:/scripts:rw"
      "/var/lib/sabnzbd/shared:/shared:rw"
      "/var/lib/sabnzbd/incomplete:/incomplete-downloads:rw"
      "/var/lib/sabnzbd/complete:/complete:rw"
    ];
    ports = [
      "7979:7979/tcp"
    ];
    dependsOn = [
      "gluetun"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network=container:gluetun"
    ];
  };
  systemd.services."podman-sabnzbd" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    partOf = [
      "podman-compose-downloads-root.target"
    ];
    wantedBy = [
      "podman-compose-downloads-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-downloads-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
