# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."dispatcharr" = {
    image = "ghcr.io/dispatcharr/dispatcharr:latest";
    environment = {
      "CELERY_BROKER_URL" = "redis://localhost:6379/0";
      "DISPATCHARR_ENV" = "aio";
      "DISPATCHARR_LOG_LEVEL" = "info";
      "REDIS_HOST" = "localhost";
    };
    volumes = [
      "dispatcharr_dispatcharr_data:/data:rw"
    ];
    dependsOn = [
      "gluetun"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network=container:gluetun"
    ];
  };
  systemd.services."podman-dispatcharr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-dispatcharr_default.service"
      "podman-volume-dispatcharr_dispatcharr_data.service"
    ];
    requires = [
      "podman-network-dispatcharr_default.service"
      "podman-volume-dispatcharr_dispatcharr_data.service"
    ];
    partOf = [
      "podman-compose-dispatcharr-root.target"
    ];
    wantedBy = [
      "podman-compose-dispatcharr-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-dispatcharr_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f dispatcharr_default";
    };
    script = ''
      podman network inspect dispatcharr_default || podman network create dispatcharr_default
    '';
    partOf = [ "podman-compose-dispatcharr-root.target" ];
    wantedBy = [ "podman-compose-dispatcharr-root.target" ];
  };

  # Volumes
  systemd.services."podman-volume-dispatcharr_dispatcharr_data" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect dispatcharr_dispatcharr_data || podman volume create dispatcharr_dispatcharr_data
    '';
    partOf = [ "podman-compose-dispatcharr-root.target" ];
    wantedBy = [ "podman-compose-dispatcharr-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-dispatcharr-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
