# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/2be3b85a-626c-446e-90f0-4432b649f618";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/1C9F-41E2";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/mnt/disk1" = {
    device = "/dev/disk/by-uuid/20c86629-9c4b-4d0b-9689-72bcc6f0a2ab";
    fsType = "ext4";
    # options = [ "defaults" "mode=755" ];
  };

  fileSystems."/mnt/disk2" = {
    device = "/dev/disk/by-uuid/2d873ef8-0885-40c9-a045-2626bc257c5a";
    fsType = "ext4";
  };

  fileSystems."/mnt/disk3" = {
    device = "/dev/disk/by-uuid/abeb557a-34cf-46ce-949b-6a427510b90f";
    fsType = "ext4";
  };

  fileSystems."/mnt/disk4" = {
    device = "/dev/disk/by-uuid/a5f6717f-ad9e-4b4a-9b28-6c9430513b95";
    fsType = "ext4";
  };

  fileSystems."/mnt/disk5" = {
    device = "/dev/disk/by-uuid/39d28bba-8196-4ca4-9c77-c2ce475c679d";
    fsType = "ext4";
  };

  environment.systemPackages = with pkgs; [ mergerfs ];

  fileSystems."/mnt/data" = {
    device = "/mnt/disk*";
    fsType = "fuse.mergerfs";
    options = [
      "allow_other"
      "cache.files=off"
      "dropcacheonclose=false"
      "category.create=pfrd"
      "func.getattr=newest"
    ];
    depends = [
      "/mnt/disk1"
      "/mnt/disk2"
      "/mnt/disk3"
      "/mnt/disk4"
      "/mnt/disk5"
    ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
